update

diff --git a/tarka b/tarka
--- a/tarka
+++ b/tarka
@@ -1,12 +1,13 @@
 #!/bin/sh
 #
-# Portable script to for backups using rsync, gpg and tar
+# Portable script for backups using rsync, gpg and tar
 #
 # Commentary:
 # Works transparently over SSH by mounting with sshfs
 # Unencrypted files are never exposed on the remote system
 # Root privileges are required to preserve permissions (see tar man page for -p)
 # Due to the critical nature of this script, MAXIMIZE THE LINES OF CODE NOT WRITTEN.
+# Install ispell for nice backup identifiers
 #
 # Requirements:
 # GNU date and tar
@@ -15,7 +16,6 @@
 # list command should list backup size
 # test keep_in (keep command)
 # test on directories with spaces?
-# checksums (with cksum or gpg sign functionality)
 #
 # Code:
 #set -x
@@ -128,6 +128,7 @@ parse() { # parse backup file name and their metadata eg:
     ptag="${pmeta#*+}"
     ptag="${ptag#*--}"
     ptag="${ptag%%.*}"
+    test "$ptag" = "$pnr" && ptag=
     case "$pmeta" in
         *.snr*) ptag="#SNAR#";;
     esac
@@ -201,29 +202,52 @@ untar() {
     test -e "$(merge_dir "$1" "$2")" || exits "assertion failed; merge directory is absent"
 }
 
+check() {
+    ! test -s "$repo/check.sum" && return
+    (cd "$repo" && while IFS= read -r i; do list0 "${i%: *}"; printf "%s\n" "${i##*: }"; done<<EOF) || exits "verifying checksum failed"
+$(sha256sum -c "$repo/check.sum")
+EOF
+}
+
+sum() {
+    (cd "$repo" && sha256sum "$@">> "$repo/"check.sum) || exits "generating checksum failed"
+}
+
+remsum() {
+    (cd "$repo" && sed "/  ${1##*/}/d" check.sum >check-new.sum && mv check-new.sum check.sum) || \
+        exits "failed updating checksum file"
+}
+
 # shellcheck disable=SC2317
 remhash_latest() {
     echo "-- LATEST TO REMOVE:"
     latest="$(latest "$1" "$2")"
     list "$latest"
     yesnp
+    # TODO remove snar
     rm "$latest"
+    remsum "$latest"
 }
 
 remhash() {
     echo "-- TO REMOVE:"
     for i in "$repo"/"$(realmangle "$1")"*"=$2+"*.gpg; do
         test -e "$i" || exits "backup for $1 $2 doesn't exist"
-        list "$i"
+        list "$i" #-1
     done
     yesnp
     for i in "$repo"/"$(realmangle "$1")"*"=$2+"*.gpg; do
         rm "$i"
+        remsum "$i"
     done
 }
 
 rand() {
-    tr -dc a-z0-9 </dev/urandom | head -c 8
+    if test -r /usr/share/dict/words; then # requires ispell
+        grep "^[^']\{4,8\}$" /usr/share/dict/words | shuf -n1
+    else
+        tr -dc a-z0-9 </dev/urandom | head -c 8
+    fi
 }
 
 genhash() { # each set of incremental backups is grouped by hash
@@ -236,20 +260,23 @@ genhash() { # each set of incremental backups is grouped by hash
 }
 
 listfmt() {
-    printf "%s" "%-40s\t%12s %-5s\t%8s\t%8s %02s\t%s\n"
+    printf "%s" "%-40s\t%12s %-5s\t%8s\t%8s %02s\t%-12s"
 }
 
 list() {
     parse "$1"
-    test -n "$2" && test "$ptag" = "#SNAR#" && return
-    psize="$(du -k "$1" | cut -f1)"
+    test -n "$2" && test "$2" -eq -1 && test "$ptag" = "#SNAR#" && return
+    test -e "$1" && psize="$(du -k "$1" | cut -f1)" || psize="--"
     # shellcheck disable=SC2059
     printf "$(listfmt)" "$psrc" "$pday" "$ptime" "$psize" "$phash" "$pnr" "$ptag"
+    test "${2--1}" -ne 0 && printf "\n"
 }
+
+list0() { list "$1" 0; }
 
 lists() {
     # shellcheck disable=SC2059
-    test -z "$3" && printf "$(listfmt)" "src" "day" "time" "size" "hash" "nr" "tag"
+    test -z "$3" && printf "$(listfmt)\n" "src" "day" "time" "size" "hash" "nr" "tag"
     for i in "$repo/${1+$(realmangle "$1")}"*"${2:+=$2+}"*.gpg; do
         test -e "$i" || break
         list "$i" -1
@@ -263,17 +290,17 @@ sync() {
 targ() { # tar with -g
     dst="$fetchdir/$(dst "$1" "$2")"
     xdir="$(merge_dir "$1" "$2")"
-    snar="$dst.snar"
     if test "$isfull" -eq 0; then
         snar="$fetchdir/${latest#"$repo"}"
         snar="${snar%.*}"
         snar="${snar%.*}.snr"
         ! test -e "$snar" && exits "snar at $snar doesn't exist"
+        cp "$snar" "$dst.snr"
     fi
-    echo "-- tar with $dst.snr..."
-    tar -cpf "$dst.tar" "$xdir" -g  "$snar" -P --lzma --xform="s|^${fetchdir}/||" || exits "archiving $1 failed"
-    rm "$repo/${snar#"$fetchdir"}.gpg"
-    mv "$snar" "$dst.snr"
+    echo "-- tar"
+    list "$dst.snr"
+    tar -cpf "$dst.tar" "$xdir" -g "$dst.snr" -P --lzma --xform="s|^${fetchdir}/||" || exits "archiving $1 failed"
+    rm -r "$xdir"
 }
 
 isrepo() {
@@ -354,8 +381,8 @@ backup() {
         list "$fetchdir/$i"
         rsync -z "$fetchdir/$i" "$repo/"
     done
+    sum "$(dst)".tar.gpg "$(dst)".snr.gpg
     touch "$repo/.repo"
-    rm -r "$xdir"
 }
 
 delete() {
