functions

diff --git a/tarka b/tarka
--- a/tarka
+++ b/tarka
@@ -1,8 +1,7 @@
 #!/bin/sh
 #
 #
-#
-#
+# set -xe
 
 parse() {
     rest="$(basename "$1")"
@@ -42,45 +41,90 @@ untar() {
     done
 }
 
-[ "$1" = full ] && isfull=1 && shift
+mangle_path() {
+    p="${1%/}"
+    p="$(echo "${p#/}" | tr '/' '~')"
+}
 
-src=$(realpath "$1")
-repo=${2%/}
-tag=${3:-}
-date=$(date +'%Y-%m-%d__%H-%M')
-src_mangled="${src%/}"
-src_mangled=$(echo "${src_mangled#/}" | tr '/' '~')
-latest "$src_mangled"
+setsrc() {
+    src=$(realpath "$1")
+    mangle_path "$src"
+    src_mangled="$p"
+}
 
-if [ -n "$isfull" ] || [ ! -e "$latest" ]; then
-    isfull=1
-    hash="$(date +%s | md5sum | head -c 8)"
-    nr="0"
-else
-    parse "$latest"
-    hash="$phash"
-    nr="$((pnr+1))"
-fi
+# setargs REPO SRC [TAG]
+setargs() {
+    setsrc "$1"
+    tag=${2:-}
+    date=$(date +'%Y-%m-%d__%H-%M.%S')
+    latest "$src_mangled"
 
-group="${repo}/${src_mangled}~${hash}"
-dst="${repo}/${src_mangled}~${date}=${hash}!${nr}${tag:+--}${tag}"
+    if [ -n "$isfull" ] || [ ! -e "$latest" ]; then
+        isfull=1
+        hash="$(date +%s | md5sum | head -c 8)"
+        nr="0"
+    else
+        parse "$latest"
+        hash="$phash"
+        nr="$((pnr+1))"
+    fi
 
-[ -z "$isfull" ] && untar "$src_mangled" "$hash"
-# exit 0
+    group="${repo}/${src_mangled}~${hash}"
+    dst="${repo}/${src_mangled}~${date}=${hash}!${nr}${tag:+--}${tag}"
+}
 
-echo "----------"
-printf "%-15s : %s\n" "group" "$group"
-printf "%-15s : %s\n" "latest" "$latest"
-printf "%-15s : %s\n" "destination" "$dst"
-echo "----------"
+list() {
+    mangle_path "$1"
+    printf "%-40s %-30s %s\n" "src" "date" "nr"
+    for i in "$repo/"${p}*.tar; do
+        parse "$i"
+        printf "%-40s %-30s %s\n" "$psrc" "$pdate" "$pnr"
+    done
+}
 
-# exit 0
-rsync -avz \
-      "$src/" \
-      "${group}"
+sync() {
+    # exit 0
+    rsync -avz --delete \
+          "${1}/" \
+          "${2}"
+    # --exclude-from="$0-ignore" \
+}
 
-# --exclude-from="$0-ignore" \
+roll() {
+    tar cvf "${2}.tar" "${1}" -g "${1}.snar" --xform="s|^${repo}/||"
+}
 
-tar cvf "$dst.tar" "${group}" -g "${group}.snar" --xform="s|^${repo}/||"
-rm -rf "${group}"
-echo "-- ok"
+usage() {
+    echo "$0 cmd repo cmd_args"
+    exit 1
+}
+
+main() {
+    test -n "$1" || usage
+    test -n "$2" || usage
+
+    cmd="$1"
+    shift
+    repo=${1%/}
+    case "$cmd" in
+        f*)  isfull=1 && shift && break;;
+        i*)  isinc=1  && shift && break;;
+        l*)  isls=1   && list "$@" && exit;;
+        *) echo "invalid operation: $cmd;" >&2
+           exit 1;;
+    esac
+
+    setargs "$1" "$2"
+    # [ -z "$isfull" ] && untar "$src_mangled" "$hash"
+
+    printf "%-15s : %s\n" "group" "$group"
+    printf "%-15s : %s\n" "latest" "$latest"
+    printf "%-15s : %s\n" "destination" "$dst"
+    echo "----------"
+
+    sync "$src" "$group"
+    roll "$group" "$dst"
+    rm -rf "${group}"
+}
+
+main "$@"
